### ISSUE TITLE
Add goal model

### ISSUE THREAD

**Issue by TommyByrne** [headwayio/agile-results#12]

**Comment by TommyByrne** [comment]
Question:

Each User will have many goals 3 to be exact for each level of goal: daily, weekly, monthly, yearly.  And each  goal will have  a title, description, due_date, completed, and user_id attribute.   Would you also add a type attribute in the goals model to declare if it was a daily goal, weekly goal ....  instead of having completely different models for each goal level?

**Comment by ccschmitz** [comment]
@TommyByrne I don't think we would want to do separate models either. Personally, I think using `due_date` will be enough. We could also add a `start_date` in case you want to set a goal for the future (e.g. planning your week and scheduling items for later in the week). Then we just help with the creation of daily, weekly, monthly and yearly goals in the UI.

Does that make sense? What do you think, @jondkinney?

**Comment by TommyByrne** [comment]
@ccschmitz What about if we want to add some sort a scoring system based of goal type.  For example daily = 1 weekly =5 monthly =10  yearly= 50 or something.   

So with the Rule of three  the `User` would have 3 goals per day, per week per month per year.  All in some  way trying to help achieve the bigger goals set(yearly).

 This helping to create a metric  to monitor the individuals progress and  better see on a weekly, monthly basis how they are improving reaching the goals set forth.  

Would that be easier if `type` was included or still can be created using a `due_date` ?

Not sure if this makes sense but We can have a brain dump when you get back as well.

**Comment by jondkinney** [comment]
I think having `type` is fine. You'd be making a polymorphic goal resource in that case. With that setup you can have one `goals` table, but each goal type can have it's own model & relationship to the user.

This adheres to the single responsibility principal better and will allow the system to grow / change more easily. The alternative would be a lot of conditional logic in the single goal model to check the type to perform goal-type-specific business logic.
